BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
  XXXX XXXXXX XXXX XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XX
    XXXX XXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXXXX XXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXX XXXX XXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXX
            XXXXXXX
              XXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXX
            XXXXXXXX
            XXXXXXX
            BBB BBBB BB BBBB
            BBBB BBBBBBBBBBBBBBBBBBBB
              XXXX
                XXXX
                  XXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                      XX XXXXXXXX
        XXXX XXXXXBB BBBBBBBBBBBBB
            BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                            XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXX
                XXXX
                  XXXXXXXXXX
                XXXXX
                XXXX
                  XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXX
                    
                
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    BBBBBBBBBBXXXXXXX
                XXXXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBXX
                  XXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXX
                  X
                XXXXX
              XXXXX
              BBBBBBB
            BBBBBB
              BB BBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXFFFFFFFFFFFFFFFXXXXX
    XXXXX
    XXXX
        XXXX
            XX XXXXXX
            XX XXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX XXXXX
            X XFFFFFFFFFFFFFFF
        XXXXX
    XXXXX
    BBBBB

    XXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXX
            XFFFFFFFFFFFFFFF
        XXXXX
    XXXXX
    XXXXXXXX
XXXXXXXX


XXXXXXXX X XXXXXXXXXXX
XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
    
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
BBBBBBBBBB
XXXXXXX
        XXXXXX

          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXX XX XXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
  XXXXXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXX
BBBBBBBB
