BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXXX
BBBBBBBB

BBBBB BBBBB
XXXXX  
BBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXX XXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX XXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXX XXXX XXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXXXXXXX XXXXX
XXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXX
XXXXX
XXXXXXX
    XXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXX
    XXXX
        XXXXXXXXXXXXXXXXX
        XXXX XXXXX
    XXXXX
    XXXX
        XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
    XXXXX
    XXXX
        XXXXXXXXXXXXXXXX
        XXXXX  XXXXX
    XXXXX
    XXXX
        XXXXXXXXX XXXXXXXXXXX
        XXXXXXXXX
    XXXXX
    XXXX
        XXXXXXXXXXXXXXX
        XXXXBB BBBBBBBBBBXXXXBBBBXXXXXXX XXXXXXXBBBBBXXXXX
    XXXXX
XXXXXXXX

XXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXX
            XXXXXXXXX XXXXXXXXXXX
            XXXXXXX
            XXXX
                XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
            XXXXX
            XXXXXXXX
            XXXXXXX
            BBB BBBB BB BBBBBBBBBBBBBBB
            XXX XXXXXXXXXXBBBBB BBB BBBXX
                XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX
            XXXXX
            BBBBBB
            XXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXXXXXX
        XXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB