BBBB BBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXX

XXXXXX

    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX

    XXXX XXX XXXX XXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX

XXXXXXX

XXXXXX

    XXXXXXXX
        XXXX XXXXXX XXXXX XXX
       XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XX
                XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXX
                   XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                       XXXX XXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                                    XXXX XXXXXXXXXXXXX
                                        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXX
                                        XXXXX XXXXXXXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXX
                                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                                XXXXXXXXX
                                            XXXXXX
                                        XXXXXXX
                                    XXXXXX
                                    XXX XXXXXXXXXXXXXXXXXXXX     
                                        XXXXXXXX XXXX XXX XXXXXXXX
                                    XXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                   XXXX                                          
                                        XXXXXX XXXXXXBBB BBBBBBXXXX XXXXXXX XXXXXXXXX
                                       XXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXX XXXX  XXXXXXXXX
                                       XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXX
                                       XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXX
                                       XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                   XXXXX
                                XXXXXX
                            XXXXXX
                       XXXXXX
                   XXXXXX
                XXXXXX
               XXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX XXXX XXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                                XXXX XXXXXXXXXXXXX
                                  XX XXXXXXBBB BBBBBBBBBBBXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                                XXXX XXXXXXXXX XXX
                                XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXX
                                    XXXXX                                                
                                        XXX XXXXXXXXXXXXXXXX                                                                                                                                     
                                            XXXXXX XXXXXXBBB BBBBBBBBBBBXXXXXXXXXXXXXXX
                                           XXX XXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXX
                                            XXXXX
                                            XXXXXX XXXXXXXXXXXXXXXXX
                                            XXXXX
                                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXX 
                             XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXX XXXXXXXXXXXXX XXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXXX XXXXXXX XX
                                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXX
                                                XX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                                            XXXXXX
                                        XXXXXX
                                     XXXXX


                                    XXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX
                                    XXXXX
                                   XXX XXXXXXXXXXXXX XXXXXXXXXXXX
                                   BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                        XXXXXXX  
                                        XX XXXXXXBBB BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                                        BBBB
                                        XX XXXXXXBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                                        BBBBB

                                   XXXXX
                                XXXXX
                            XXXXXX
                            XXXX XXXXXX XXXX XXX
                            XXXX XXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
               XXXXXX
            XXXXXX
       XXXXXX
        XXXX XXXXXX XXX XXX
    XXXXXXXXX

    XXXX XXXXXX XXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XX
        XXXX XXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXX XXXX XXXXXX


    XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXX
                                XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX
                        XXXXXX
                         XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XXXXXX
                                BBB BBBBBBBB BB BBBBBBBBBB
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BB BBBBBBBB
                        XX XXXXXXXXXXXX
                                    BBBBBXXXXX
                                XXXXXX
                                BBBBBB
                            XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX
                             BBB BBBBBBB BB BBBBBBBB
                            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB X XXXXXXXXXXXXXXXXX X
                                    XX XXXXXXXXXXXX
                                    XXXX XX XXXXXXXXXXXX XXXXX
                                      XXXXXXX
                                    XXXXXXXX
                                XXXXXX
                            XXXXXX
                        BBBBBB
                XXXXXX

                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB
                        XXXXXX
                    XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX




    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXX
                            XXXXXXXXXXX XX XXXXXXXXXXX XXXX XXXXXXXXXXXX XXX XXXXXXXXX XX XXXX XXXXXXXXX XXXXXXXXXX XX XXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXX
                            XXXXX XXXXX XXXXXXXXXX
                        XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXX XXXXXX XXXXXX XXXX XXX XXX

    XXXX XXXX XXXXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX XXXXXXXX XXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXX XXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX 
                XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXX XXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXX XXXXXX XXXXXX

    XXXX XXXXXXXXX XXXX XXXX XXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXX X XXXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXX
                            XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXX XXXXXXXXX XXXX XXX XXX

    XXXXXXXX
        XXXX XXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                       XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                         XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                              XXXX XXXX XXX
                             XXXX XXXXXXXXXXXXXXXXXXXX
                                 XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                             XXXXXX
                             XXXX XXXXXXXXXXXXXXXXXXXXXX
                                 XXXX XXXXXXXXXXXXXXXXXXXX
                                     XXXXXXXX XXXXX XXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXX XX XXXXXXX XXXXXX XXXXXXXXXX XX XXXXXXXXXXX
                                XXXXXX
                             XXXXXX
                         XXXXXX
                       XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXX XXXXXXXXXX
                                XXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXX  XXXXXXX XXXXXXXXXXX
                                XXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX
                                XXXX
                                    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXX
                                XXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXX
                                XXXX
                                 XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
                                 XXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
                                 XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                 XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                 XXXXXX XXXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXX
                             XXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXX XXXXXX XXX
                XXXX XXXXXXXXXXXX
                 XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                     XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXX XXXX XXXX XX XXXXXXXX XXXXX XX XXXXXXXX XXXXXXXX XX XXXXXXXX XXXXX XX XX XXXX XXX
  XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX X XXXX XXXXXXXX XX XXXX XXXX XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXX XXXX XX XXXXXXXX XXXXX XX XXXXXXXX XXXXXXXX XX XXXXXXXX XXXXX XX XX XXXX XXXXXXX                   XXXXXX
                 XXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                     XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                         XXXX XXXXXX XXX
                         XXXX XXXXXXXXXXXXXXXXXXXXXX
                             XX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                             XX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                             XX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                             XX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                         XXXXXX
                     XXXXXX
                 XXXXXX
             XXXXXX
            XXXXXX
        XXXXXX
 
        XXXX XXXXXX XXXXXX
    XXXXXXXXX

XXXX XX XXXX XXX
        XXXX XXX XX XXXXXX XXXXXXX XXXX XXXX XXXX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        
        XXXX XXXXXXX XXXXXXX XXXXXXXXX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXX XXXXXX XXXXXX XXXX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

        XXXX XXXXXX XXXXX X XXXXXXXXXXXX XXXXXXX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX

        XXXX XXX XXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

        XXXX XXXXXXXXX XXXXXXXXXXXX XXXXXX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        
        XXXX XXXXXXX XX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        
        XXXX XXXXXX XXXXXXXX XXXX XXXXXX XXX    
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBXXXXXXXXXXX

        XXXX XXXXXX XX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXX XXXXXX XX XXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX


XXXXXXX

XXXXXXX