XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXXXX XXXXXXXXX
XXXX
    XXXXXXX XXX XXXXX
XXXXX XXXXXXXXXXXXXXXXXX
    FFFFFFF FF FF
XXXXXXX
XXXX
XXXXXXXX XXXXXXX
XXX
     XXXX
    XXXX
    XXXX
    X 
XXXX

XXXXXXXXX XXXXXXXXXXX
XXXXXXX
    XXXXXXX
    XXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
    XXXXX
    XXXXXXXX
XXXXXXX
BBB BBBB BB BBBBBBBBBBBBBBB
XXX XXXXXXXXXXBBBBB BBB BBBXX
    XXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX
XXXXX
BBBBBB
XXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX
XXXXX
XXXXXXXX
XXXXXXXX
XXXXX XXXXXXXBB BBBBBBBBBBXXXXBBBBXXXXXXXBBBBBXX
BB BBBBBBBBBBXXXXBBBBXXXXXXX XXXXXXXBBBBB
XXXXXXX
XXXXXXX
XXXXXXX