BBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBXXXX XXXX XXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXX XXXXXXXXXXXX
XXXXXX XXX XXXX XXXX XXXXXXX XXXXX XXX XXXXXXXXX XXXXXXXXX
XXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


BBBBBBBBBB
XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
XXXXXXX
BBBBBBBB