BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBB
    XXXX XXXXXX XXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XX
        XXXX XXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXX XXXX XXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XX XXX XXXXXXXXXX
                            XXXXXXXX XXX XXXXXXXX XXXXX XXXX XX XXXXXXX XXX XXXXXXXXXX
                                XXXXXXXXX XXX X XXXX XXXXXXX XX XXXX XX XXXXXXX
                            XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX XXXX X XXXX
                                XXXXXX XXXX XX XXXXXXXX
                            XXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                BBBBBBBBBB
                                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
                                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX


                                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                                    XXXXXX
                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                        XXX XX
                                    XXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX
BBBBBBBB