XXXX XXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXX
BB BBBBBBBBBBBBBBBBB
     XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
BBBBB
XXXX  XX X
BB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                        XXXXXX
BBBBB
XXXXXXX
XXXXXX