BBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBXXX XX XXXXXX XXXXBBBBBBBB

BBBBB BBBBBBB
XXXXX
  XXXXXXX XX XXXXXX XXXXXXXXX
  XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
  XXXXXXXXXXXXX
  XXXX XXXX XXX XXXXXXXX XXXXXX XXXXXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXX XXXXXX XXXXXX XXXXXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX
    XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX XX
    XX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX X
      XX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
      X

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX X
          XXXXXXXX XXXXXXXXXXXXX XXXXXXXX
          XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
          XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX
        XX
        XXXXXXX X
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        X
      XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXX

          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX X
            XX XXXXXXXXXXXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX
            X
            XX XXX XXXXX XX XXXX XX XXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
            XX XXXXXX XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX
        XX XXXXXXX
      XXX
    XXX
  XXXXXXXXX
BBBBBBBB